use std::net::{SocketAddr, TcpListener};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use clap::{Parser, Subcommand};
use cmfd_consensus::forgematrix::target_with_leading_zero_bits;
use cmfd_node::p2p::{spawn_inbound_listener, spawn_static_peer_polling};
use cmfd_node::peer::{PeerLimits, StaticPeerConfig};
use cmfd_node::pool::{
    DEFAULT_POOL_ADDRESS, DEFAULT_SHARE_LEADING_ZERO_BITS, PoolServerConfig, certificate_sha256,
    generate_pool_certificate, spawn_pool_server,
};
use cmfd_node::{
    DEFAULT_DATA_DIR, DEFAULT_MINING_ATTEMPTS, DEFAULT_P2P_ADDRESS, DEFAULT_RPC_ADDRESS, Node,
    default_miner_destination, parse_miner_destination, serve_rpc_shared, unix_time_seconds,
};
use serde_json::json;

#[derive(Debug, Parser)]
#[command(
    name = "cmfd-node",
    version,
    about = "CommonFoundry private multi-node Devnet-0 runtime"
)]
struct Cli {
    #[arg(long, global = true, default_value = DEFAULT_DATA_DIR)]
    data_dir: PathBuf,
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Run the loopback RPC and private-network P2P services.
    Run {
        #[arg(long, default_value = DEFAULT_RPC_ADDRESS)]
        bind: SocketAddr,
        #[arg(long, default_value = DEFAULT_P2P_ADDRESS)]
        p2p_bind: SocketAddr,
        /// Static private peer address. Repeat for multiple peers.
        #[arg(long = "peer")]
        peers: Vec<SocketAddr>,
    },
    /// Mine, validate, persist, and apply one Devnet-0 block locally.
    MineOnce {
        /// 32-byte x-only Schnorr public key as 64 hex characters.
        #[arg(long)]
        miner: Option<String>,
        #[arg(long, default_value_t = DEFAULT_MINING_ATTEMPTS)]
        attempts: u64,
    },
    /// Replay the block log and print current offline node status.
    Status,
    /// Generate a self-signed TLS certificate and print its required SHA-256 pin.
    PoolCertificate {
        /// Output path for the DER-encoded self-signed certificate.
        #[arg(long)]
        certificate: PathBuf,
        /// Output path for the DER-encoded PKCS#8 private key.
        #[arg(long)]
        private_key: PathBuf,
    },
    /// Run the authenticated, non-Stratum Devnet-0 pool service.
    PoolServe {
        #[arg(long, default_value = DEFAULT_POOL_ADDRESS)]
        bind: SocketAddr,
        #[arg(long, default_value = DEFAULT_P2P_ADDRESS)]
        p2p_bind: SocketAddr,
        /// Static private peer address. Repeat for multiple peers.
        #[arg(long = "peer")]
        peers: Vec<SocketAddr>,
        /// DER-encoded certificate generated by pool-certificate.
        #[arg(long)]
        certificate: PathBuf,
        /// DER-encoded PKCS#8 private key generated by pool-certificate.
        #[arg(long)]
        private_key: PathBuf,
        /// Pool-owned 32-byte x-only Schnorr block-reward destination.
        #[arg(long)]
        miner: Option<String>,
        /// Easier share target. Devnet chain work starts at 8 leading zero bits.
        #[arg(long, default_value_t = DEFAULT_SHARE_LEADING_ZERO_BITS)]
        share_leading_zero_bits: u16,
    },
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    match cli.command {
        Command::Run {
            bind,
            p2p_bind,
            peers,
        } => {
            let node = Node::open(&cli.data_dir)?;
            let status = node.status()?;
            let shared = Arc::new(Mutex::new(node));
            let limits = PeerLimits::default();
            let p2p_socket = TcpListener::bind(p2p_bind)?;
            let p2p_address = p2p_socket.local_addr()?;
            let inbound = spawn_inbound_listener(Arc::clone(&shared), p2p_socket, limits)?;
            let poller = if peers.is_empty() {
                None
            } else {
                Some(spawn_static_peer_polling(
                    Arc::clone(&shared),
                    StaticPeerConfig {
                        listen_address: p2p_address,
                        peers: peers.clone(),
                        limits,
                    },
                    Duration::from_secs(2),
                )?)
            };
            println!(
                "{}",
                serde_json::to_string_pretty(&json!({
                    "rpc": bind.to_string(),
                    "p2p": p2p_address.to_string(),
                    "static_peers": peers.iter().map(ToString::to_string).collect::<Vec<_>>(),
                    "status": status,
                    "warning": "private, valueless Devnet-0; peer compatibility is not identity authentication or encryption"
                }))?
            );
            let rpc_result = serve_rpc_shared(shared, bind);
            let poll_result = match poller {
                Some(poller) => poller.stop(),
                None => Ok(()),
            };
            let inbound_result = inbound.stop();
            rpc_result?;
            poll_result?;
            inbound_result?;
            Ok(())
        }
        Command::MineOnce { miner, attempts } => {
            let miner_destination = match miner.as_deref() {
                Some(value) => parse_miner_destination(value)?,
                None => default_miner_destination(),
            };
            let mut node = Node::open(&cli.data_dir)?;
            let block = node.mine_once(miner_destination, unix_time_seconds()?, attempts)?;
            println!(
                "{}",
                serde_json::to_string_pretty(&json!({
                    "accepted": true,
                    "height": block.challenge.height,
                    "block_id": hex::encode(block.block_id()),
                    "proof_type": "forgematrix-v2-reference",
                    "miner": hex::encode(miner_destination),
                    "used_insecure_default_miner": miner.is_none(),
                    "status": node.status()?,
                }))?
            );
            Ok(())
        }
        Command::Status => {
            let node = Node::open(&cli.data_dir)?;
            println!("{}", serde_json::to_string_pretty(&node.status()?)?);
            Ok(())
        }
        Command::PoolCertificate {
            certificate,
            private_key,
        } => {
            let info = generate_pool_certificate(certificate, private_key)?;
            println!(
                "{}",
                serde_json::to_string_pretty(&json!({
                    "certificate": info.certificate_path,
                    "private_key": info.private_key_path,
                    "certificate_sha256": hex::encode(info.certificate_sha256),
                    "format": "DER certificate and DER PKCS#8 private key",
                    "warning": "pin this exact SHA-256 value in every Devnet pool client"
                }))?
            );
            Ok(())
        }
        Command::PoolServe {
            bind,
            p2p_bind,
            peers,
            certificate,
            private_key,
            miner,
            share_leading_zero_bits,
        } => {
            if share_leading_zero_bits >= 8 {
                return Err(
                    "pool share-leading-zero-bits must be between 0 and 7 on Devnet-0".into(),
                );
            }
            let miner_destination = match miner.as_deref() {
                Some(value) => parse_miner_destination(value)?,
                None => default_miner_destination(),
            };
            let certificate_der = std::fs::read(&certificate)?;
            let private_key_der = std::fs::read(&private_key)?;
            let pin = certificate_sha256(&certificate_der);
            let node = Arc::new(Mutex::new(Node::open(&cli.data_dir)?));
            let limits = PeerLimits::default();
            let p2p_socket = TcpListener::bind(p2p_bind)?;
            let p2p_address = p2p_socket.local_addr()?;
            let inbound = spawn_inbound_listener(Arc::clone(&node), p2p_socket, limits)?;
            let poller = if peers.is_empty() {
                None
            } else {
                Some(spawn_static_peer_polling(
                    Arc::clone(&node),
                    StaticPeerConfig {
                        listen_address: p2p_address,
                        peers: peers.clone(),
                        limits,
                    },
                    Duration::from_secs(2),
                )?)
            };
            let mut config =
                PoolServerConfig::devnet(bind, certificate_der, private_key_der, miner_destination);
            config.share_target = target_with_leading_zero_bits(share_leading_zero_bits);
            let pool = spawn_pool_server(node, config)?;
            println!(
                "{}",
                serde_json::to_string_pretty(&json!({
                    "pool": pool.local_addr().to_string(),
                    "p2p": p2p_address.to_string(),
                    "static_peers": peers.iter().map(ToString::to_string).collect::<Vec<_>>(),
                    "protocol": "CMFD Devnet pool v1 (not Stratum)",
                    "tls": "TLS 1.3 with an exact certificate SHA-256 pin",
                    "certificate_sha256": hex::encode(pin),
                    "share_leading_zero_bits": share_leading_zero_bits,
                    "block_reward_destination": hex::encode(miner_destination),
                    "used_insecure_default_miner": miner.is_none(),
                    "accounting": "session-only accounting records; nonwithdrawable; not funds; not an on-chain balance or payout"
                }))?
            );
            // Keep all service handles alive; their Drop implementations
            // signal their worker threads during any unwinding shutdown.
            let _services = (pool, inbound, poller);
            loop {
                std::thread::park();
            }
        }
    }
}
