[package]
name = "common-foundry-wallet"
version = "0.1.0-devnet.3"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "common_foundry_wallet"
path = "src/lib.rs"

[[bin]]
name = "common-foundry-wallet"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
cmfd-node = { path = "../../../crates/cmfd-node" }
hex.workspace = true
serde.workspace = true
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-single-instance = "=2.4.3"
